In [121]:
import numpy as np

In [122]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("samayashar/stock-market-simulation-dataset")

print("Path to dataset files:", path)

Path to dataset files: /home/kuba/.cache/kagglehub/datasets/samayashar/stock-market-simulation-dataset/versions/1


In [123]:
import os

print(f"Zawartość folderu kagglehub: {os.listdir(path)}")

Zawartość folderu kagglehub: ['synthetic_stock_data.csv']


In [124]:
import os

# Define the file path using os.path.join
file_path = os.path.join(path, "synthetic_stock_data.csv")

# Load the CSV file using NumPy
text_data = np.loadtxt(file_path, delimiter=',', skiprows=1, usecols=list(range(0,3)), dtype=str)
numeric_data = np.loadtxt(file_path, delimiter=',', skiprows=1, usecols=list(range(3,13)), dtype=float)

In [125]:
text_data

array([['2022-01-01', 'Uber', 'Technology'],
       ['2022-01-02', 'Tesla', 'Automotive'],
       ['2022-01-03', 'Panasonic', 'Finance'],
       ...,
       ['2024-09-24', 'Goldman Sachs', 'Energy'],
       ['2024-09-25', 'Lyft', 'Aerospace'],
       ['2024-09-26', 'Boeing', 'Energy']], shape=(1000, 3), dtype='<U17')

In [126]:
numeric_data

array([[ 1.00000000e+02,  1.01036120e+02,  9.74778094e+01, ...,
         1.63089742e-01,  4.74843578e-02,  9.39231878e-01],
       [ 1.00071106e+02,  1.02037960e+02,  9.71526751e+01, ...,
         2.88514642e-01,  2.24720855e-02,  4.69417141e-01],
       [ 9.98578278e+01,  1.01517497e+02,  9.81080968e+01, ...,
         2.22182675e+00,  1.99908865e-02,  3.99193066e-01],
       ...,
       [ 1.20638302e+02,  1.22485538e+02,  1.18135033e+02, ...,
         3.82841292e-01,  4.80327464e-02, -5.02405872e-01],
       [ 1.20228806e+02,  1.23124765e+02,  1.17959012e+02, ...,
         2.10380601e+00,  1.83959052e-02,  8.20433310e-01],
       [ 1.20558294e+02,  1.23699478e+02,  1.17628380e+02, ...,
         3.00841082e+00,  2.04367432e-02, -6.91168485e-01]],
      shape=(1000, 10))

### Wybieranie danych

SELECT col1, col2
FROM table;

In [127]:
numeric_data[:, [0,1]]

array([[100.        , 101.03612044],
       [100.07110557, 102.03795989],
       [ 99.85782777, 101.51749734],
       ...,
       [120.63830152, 122.48553801],
       [120.22880617, 123.12476453],
       [120.55829369, 123.69947782]], shape=(1000, 2))

### Filtrowanie wierszy

SELECT *
FROM table
WHERE age > 30;

In [128]:
text_data[text_data[:,1] == "Uber"] 

array([['2022-01-01', 'Uber', 'Technology'],
       ['2022-04-05', 'Uber', 'Technology'],
       ['2022-04-15', 'Uber', 'Consumer Goods'],
       ['2022-04-18', 'Uber', 'Energy'],
       ['2022-05-06', 'Uber', 'Aerospace'],
       ['2022-10-03', 'Uber', 'Energy'],
       ['2022-10-27', 'Uber', 'Healthcare'],
       ['2022-12-18', 'Uber', 'Finance'],
       ['2022-12-28', 'Uber', 'Healthcare'],
       ['2023-06-13', 'Uber', 'Aerospace'],
       ['2023-06-19', 'Uber', 'Automotive'],
       ['2023-10-16', 'Uber', 'Technology'],
       ['2023-12-01', 'Uber', 'Aerospace'],
       ['2024-01-25', 'Uber', 'Automotive'],
       ['2024-02-20', 'Uber', 'Automotive'],
       ['2024-07-26', 'Uber', 'Automotive'],
       ['2024-08-22', 'Uber', 'Automotive'],
       ['2024-08-28', 'Uber', 'Consumer Goods']], dtype='<U17')

In [129]:
numeric_data[numeric_data[:,3] > 100]

array([[ 1.00071106e+02,  1.02037960e+02,  9.71526751e+01, ...,
         2.88514642e-01,  2.24720855e-02,  4.69417141e-01],
       [ 1.00550082e+02,  1.02752035e+02,  9.86408634e+01, ...,
         1.93161587e+00,  4.71240734e-02,  7.37721866e-03],
       [ 1.00901312e+02,  1.03512423e+02,  9.83799530e+01, ...,
         2.86920627e+00,  4.37944931e-02,  6.58301281e-01],
       ...,
       [ 1.20638302e+02,  1.22485538e+02,  1.18135033e+02, ...,
         3.82841292e-01,  4.80327464e-02, -5.02405872e-01],
       [ 1.20228806e+02,  1.23124765e+02,  1.17959012e+02, ...,
         2.10380601e+00,  1.83959052e-02,  8.20433310e-01],
       [ 1.20558294e+02,  1.23699478e+02,  1.17628380e+02, ...,
         3.00841082e+00,  2.04367432e-02, -6.91168485e-01]],
      shape=(744, 10))

### Sortowanie

SELECT *
FROM table
ORDER BY age DESC;

#### Sortowanie rosnąco

In [130]:
text_data

array([['2022-01-01', 'Uber', 'Technology'],
       ['2022-01-02', 'Tesla', 'Automotive'],
       ['2022-01-03', 'Panasonic', 'Finance'],
       ...,
       ['2024-09-24', 'Goldman Sachs', 'Energy'],
       ['2024-09-25', 'Lyft', 'Aerospace'],
       ['2024-09-26', 'Boeing', 'Energy']], shape=(1000, 3), dtype='<U17')

In [131]:
text_data.sort(0)
text_data

array([['2022-01-01', 'AMD', 'Aerospace'],
       ['2022-01-02', 'AMD', 'Aerospace'],
       ['2022-01-03', 'AMD', 'Aerospace'],
       ...,
       ['2024-09-24', 'Wells Fargo', 'Technology'],
       ['2024-09-25', 'Wells Fargo', 'Technology'],
       ['2024-09-26', 'Wells Fargo', 'Technology']],
      shape=(1000, 3), dtype='<U17')

In [132]:
numeric_data

array([[ 1.00000000e+02,  1.01036120e+02,  9.74778094e+01, ...,
         1.63089742e-01,  4.74843578e-02,  9.39231878e-01],
       [ 1.00071106e+02,  1.02037960e+02,  9.71526751e+01, ...,
         2.88514642e-01,  2.24720855e-02,  4.69417141e-01],
       [ 9.98578278e+01,  1.01517497e+02,  9.81080968e+01, ...,
         2.22182675e+00,  1.99908865e-02,  3.99193066e-01],
       ...,
       [ 1.20638302e+02,  1.22485538e+02,  1.18135033e+02, ...,
         3.82841292e-01,  4.80327464e-02, -5.02405872e-01],
       [ 1.20228806e+02,  1.23124765e+02,  1.17959012e+02, ...,
         2.10380601e+00,  1.83959052e-02,  8.20433310e-01],
       [ 1.20558294e+02,  1.23699478e+02,  1.17628380e+02, ...,
         3.00841082e+00,  2.04367432e-02, -6.91168485e-01]],
      shape=(1000, 10))

In [133]:
numeric_data.sort(0)
numeric_data

array([[ 8.22419712e+01,  8.32694982e+01,  7.98801209e+01, ...,
         1.00925887e-02,  1.00074611e-02, -9.95846965e-01],
       [ 8.25331273e+01,  8.36113819e+01,  8.02031955e+01, ...,
         1.57045302e-02,  1.00371767e-02, -9.95353188e-01],
       [ 8.25601332e+01,  8.37014178e+01,  8.03114703e+01, ...,
         2.51327630e-02,  1.00538508e-02, -9.94583700e-01],
       ...,
       [ 1.28182190e+02,  1.31353408e+02,  1.26142448e+02, ...,
         4.98131143e+00,  4.98626263e-02,  9.96399815e-01],
       [ 1.28417848e+02,  1.32091541e+02,  1.26473368e+02, ...,
         4.98199147e+00,  4.98763687e-02,  9.96637513e-01],
       [ 1.28993218e+02,  1.32196978e+02,  1.26693358e+02, ...,
         4.99771959e+00,  4.99049129e-02,  9.98098996e-01]],
      shape=(1000, 10))

#### Sortowanie malejąco

In [134]:
text_data.sort(0)
text_data[::-1]

array([['2024-09-26', 'Wells Fargo', 'Technology'],
       ['2024-09-25', 'Wells Fargo', 'Technology'],
       ['2024-09-24', 'Wells Fargo', 'Technology'],
       ...,
       ['2022-01-03', 'AMD', 'Aerospace'],
       ['2022-01-02', 'AMD', 'Aerospace'],
       ['2022-01-01', 'AMD', 'Aerospace']], shape=(1000, 3), dtype='<U17')

In [135]:
numeric_data.sort(0)
numeric_data[::-1]

array([[ 1.28993218e+02,  1.32196978e+02,  1.26693358e+02, ...,
         4.99771959e+00,  4.99049129e-02,  9.98098996e-01],
       [ 1.28417848e+02,  1.32091541e+02,  1.26473368e+02, ...,
         4.98199147e+00,  4.98763687e-02,  9.96637513e-01],
       [ 1.28182190e+02,  1.31353408e+02,  1.26142448e+02, ...,
         4.98131143e+00,  4.98626263e-02,  9.96399815e-01],
       ...,
       [ 8.25601332e+01,  8.37014178e+01,  8.03114703e+01, ...,
         2.51327630e-02,  1.00538508e-02, -9.94583700e-01],
       [ 8.25331273e+01,  8.36113819e+01,  8.02031955e+01, ...,
         1.57045302e-02,  1.00371767e-02, -9.95353188e-01],
       [ 8.22419712e+01,  8.32694982e+01,  7.98801209e+01, ...,
         1.00925887e-02,  1.00074611e-02, -9.95846965e-01]],
      shape=(1000, 10))

#### DO ZAPAMIĘTANIA

table.sort() modyfikuje table, nic nie zwraca
np.sort(table) nie modyfikuje table, zwraca nową, posortowaną table

### Agregacje

SELECT col1, COUNT(col2)
FROM table
GROUP BY col1;

In [136]:
firmy, indeksy = np.unique(text_data[:,1], return_inverse=True)
czestosc_wystepowania = [len(text_data[text_data[:,1] == firma]) for firma in firmy]
czestosc_wystepowania

[17,
 17,
 20,
 21,
 8,
 13,
 16,
 14,
 20,
 9,
 23,
 14,
 17,
 13,
 15,
 19,
 14,
 21,
 18,
 14,
 18,
 17,
 16,
 18,
 8,
 19,
 18,
 11,
 19,
 14,
 12,
 15,
 17,
 13,
 27,
 11,
 14,
 20,
 18,
 14,
 16,
 22,
 19,
 9,
 15,
 11,
 16,
 17,
 14,
 12,
 12,
 22,
 12,
 10,
 18,
 23,
 17,
 13,
 15,
 16,
 18,
 11,
 20]

### Łączenie tabel

SELECT *
FROM table1
JOIN table2
ON table1.id = table2.id;

In [137]:
# Combine text_data and numeric_data arrays horizontally
combined_data = np.hstack((text_data, numeric_data))

combined_data

array([['2022-01-01', 'AMD', 'Aerospace', ..., '0.010092588741169584',
        '0.010007461126826525', '-0.9958469647998376'],
       ['2022-01-02', 'AMD', 'Aerospace', ..., '0.01570453024061058',
        '0.010037176674798443', '-0.9953531877361395'],
       ['2022-01-03', 'AMD', 'Aerospace', ..., '0.025132763049015572',
        '0.010053850838262548', '-0.9945837003590958'],
       ...,
       ['2024-09-24', 'Wells Fargo', 'Technology', ...,
        '4.981311432624384', '0.0498626262515593', '0.9963998153312352'],
       ['2024-09-25', 'Wells Fargo', 'Technology', ...,
        '4.981991468395277', '0.04987636874357421', '0.9966375131419134'],
       ['2024-09-26', 'Wells Fargo', 'Technology', ...,
        '4.9977195935954715', '0.04990491289005542',
        '0.9980989962072899']], shape=(1000, 13), dtype='<U32')

### Wartości NULL

SELECT *
FROM table
WHERE col1 IS/IS NOT NULL;

In [138]:
numeric_data[0:3,2] = np.nan
numeric_data

array([[ 8.22419712e+01,  8.32694982e+01,             nan, ...,
         1.00925887e-02,  1.00074611e-02, -9.95846965e-01],
       [ 8.25331273e+01,  8.36113819e+01,             nan, ...,
         1.57045302e-02,  1.00371767e-02, -9.95353188e-01],
       [ 8.25601332e+01,  8.37014178e+01,             nan, ...,
         2.51327630e-02,  1.00538508e-02, -9.94583700e-01],
       ...,
       [ 1.28182190e+02,  1.31353408e+02,  1.26142448e+02, ...,
         4.98131143e+00,  4.98626263e-02,  9.96399815e-01],
       [ 1.28417848e+02,  1.32091541e+02,  1.26473368e+02, ...,
         4.98199147e+00,  4.98763687e-02,  9.96637513e-01],
       [ 1.28993218e+02,  1.32196978e+02,  1.26693358e+02, ...,
         4.99771959e+00,  4.99049129e-02,  9.98098996e-01]],
      shape=(1000, 10))

In [139]:
maska = np.isnan(numeric_data)
numeric_data[maska]

array([nan, nan, nan])

In [140]:
numeric_data[~maska]

array([8.22419712e+01, 8.32694982e+01, 8.22419712e+01, ...,
       4.99771959e+00, 4.99049129e-02, 9.98098996e-01], shape=(9997,))

### Dodawanie kolumn

ALTER TABLE table
ADD COLUMN new_col INT;

In [141]:
new_col = np.zeros_like(numeric_data[:,0])
numeric_data = np.column_stack((numeric_data, new_col))
numeric_data

array([[ 8.22419712e+01,  8.32694982e+01,             nan, ...,
         1.00074611e-02, -9.95846965e-01,  0.00000000e+00],
       [ 8.25331273e+01,  8.36113819e+01,             nan, ...,
         1.00371767e-02, -9.95353188e-01,  0.00000000e+00],
       [ 8.25601332e+01,  8.37014178e+01,             nan, ...,
         1.00538508e-02, -9.94583700e-01,  0.00000000e+00],
       ...,
       [ 1.28182190e+02,  1.31353408e+02,  1.26142448e+02, ...,
         4.98626263e-02,  9.96399815e-01,  0.00000000e+00],
       [ 1.28417848e+02,  1.32091541e+02,  1.26473368e+02, ...,
         4.98763687e-02,  9.96637513e-01,  0.00000000e+00],
       [ 1.28993218e+02,  1.32196978e+02,  1.26693358e+02, ...,
         4.99049129e-02,  9.98098996e-01,  0.00000000e+00]],
      shape=(1000, 11))

### Operacje matematyczne

SELECT col1 + col2
FROM table;

In [142]:
numeric_data[:,0] + numeric_data[:,1]

array([165.51146943, 166.14450923, 166.26155102, 166.53277144,
       167.54893772, 167.73118553, 168.06841392, 169.25035789,
       169.92961505, 170.07231467, 170.41064096, 170.61373803,
       171.19503423, 171.4892715 , 172.2272998 , 172.52590726,
       173.24448346, 173.35994326, 173.46463844, 173.66600335,
       173.80776795, 174.00366076, 174.03228116, 174.17197871,
       174.34746861, 174.47525426, 174.69182339, 174.78952985,
       174.90214555, 175.10349712, 175.16529951, 175.22409745,
       175.39444652, 175.60171515, 175.67716921, 175.71831849,
       175.91995207, 175.97980939, 176.13096556, 176.27505358,
       176.3995175 , 176.52791692, 176.78059649, 176.83525706,
       176.87882174, 176.95905028, 177.10853637, 177.12596667,
       177.1649259 , 177.43240883, 177.53002545, 177.63123477,
       177.76641265, 177.81416688, 178.08574163, 178.17470395,
       178.42353545, 179.14528298, 179.37299313, 180.05458379,
       180.15664802, 180.37412934, 180.73293585, 181.00

### Limit wyników

SELECT *
FROM table
LIMIT 5;

In [144]:
numeric_data[:5,:]

array([[ 8.22419712e+01,  8.32694982e+01,             nan,
         8.22419712e+01,  5.01260000e+04,  1.23728605e+09,
         5.00659398e+00,  1.00925887e-02,  1.00074611e-02,
        -9.95846965e-01,  0.00000000e+00],
       [ 8.25331273e+01,  8.36113819e+01,             nan,
         8.25331273e+01,  5.02350000e+04,  1.33217361e+09,
         5.01549735e+00,  1.57045302e-02,  1.00371767e-02,
        -9.95353188e-01,  0.00000000e+00],
       [ 8.25601332e+01,  8.37014178e+01,             nan,
         8.25601332e+01,  5.04040000e+04,  2.02845037e+09,
         5.06579592e+00,  2.51327630e-02,  1.00538508e-02,
        -9.94583700e-01,  0.00000000e+00],
       [ 8.27503147e+01,  8.37824568e+01,  8.06458198e+01,
         8.27503147e+01,  5.07690000e+04,  2.11899137e+09,
         5.07363451e+00,  2.67308043e-02,  1.00657503e-02,
        -9.92595186e-01,  0.00000000e+00],
       [ 8.27969536e+01,  8.47519841e+01,  8.07592573e+01,
         8.27969536e+01,  5.08460000e+04,  2.23060333e+09,
  

### Unikalne wartości

SELECT DISTINCT col
FROM table;

In [145]:
np.unique(text_data[:,1])

array(['AMD', 'Adobe', 'Airbus', 'Alibaba', 'Amazon', 'Apple',
       'AstraZeneca', 'BMW', 'BP', 'Bank of America', 'Boeing', 'Chevron',
       'Citigroup', 'ExxonMobil', 'Ferrari', 'Ford', 'General Motors',
       'Gilead Sciences', 'Goldman Sachs', 'Google', 'HSBC', 'Honda',
       'IBM', 'Intel', 'JPMorgan Chase', 'Johnson & Johnson', 'LG',
       'Lamborghini', 'Lockheed Martin', 'Lyft', 'MasterCard',
       'Mercedes-Benz', 'Meta', 'Microsoft', 'Moderna', 'Morgan Stanley',
       'Netflix', 'Northrop Grumman', 'Novartis', 'Nvidia', 'Oracle',
       'Panasonic', 'PayPal', 'Pfizer', 'Porsche', 'Raytheon', 'Roche',
       'Salesforce', 'Samsung', 'Shell', 'Snapchat', 'Sony', 'SpaceX',
       'Spotify', 'Square', 'Tencent', 'Tesla', 'TotalEnergies', 'Toyota',
       'Twitter', 'Uber', 'Visa', 'Wells Fargo'], dtype='<U17')